# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('ruleCategories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markup', '0001_initial'),
        ('wcag20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('updated_ptr', models.OneToOneField(parent_link=True, to='examples.Updated', auto_created=True)),
                ('example_id', models.AutoField(primary_key=True, serialize=False)),
                ('permanent_slug', models.SlugField(null=True, blank=True)),
                ('title', models.CharField(max_length=512)),
                ('title_html', models.CharField(default='', max_length=1024)),
                ('title_text', models.CharField(default='', max_length=512)),
                ('description', models.TextField(null=True, verbose_name='Describe features of example', blank=True)),
                ('description_html', models.TextField(default='')),
                ('keyboard', models.TextField(null=True, verbose_name='Information on keyboard shortcuts', blank=True)),
                ('keyboard_html', models.TextField(default='')),
                ('status', models.CharField(default='acc', choices=[('acc', 'Accepted'), ('pro', 'Proposed'), ('dep', 'Deprecated')], max_length=8)),
                ('external_url', models.URLField(verbose_name='External URL to example', max_length=512, blank=True)),
                ('style', models.TextField(null=True, verbose_name='CSS code', blank=True)),
                ('style_code', models.TextField(default='')),
                ('style_source', models.TextField(default='')),
                ('html', models.TextField(null=True, verbose_name='HTML code for inside body tag', blank=True)),
                ('html_code', models.TextField(default='')),
                ('html_source', models.TextField(default='')),
                ('script', models.TextField(null=True, verbose_name='Javascript code', blank=True)),
                ('script_code', models.TextField(default='')),
                ('script_source', models.TextField(default='')),
                ('onload', models.CharField(null=True, max_length=128, blank=True)),
                ('title_override', models.CharField(null=True, max_length=512, blank=True)),
                ('order', models.IntegerField(default=0)),
                ('markup', models.ManyToManyField(null=True, to='markup.ElementDefinition', related_name='examples', blank=True)),
                ('success_criteria', models.ManyToManyField(null=True, to='wcag20.WCAG20_SuccessCriterion', related_name='examples', blank=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Examples',
                'verbose_name': 'Example',
            },
            bases=('examples.updated',),
        ),
        migrations.CreateModel(
            name='ManualCheck',
            fields=[
                ('updated_ptr', models.OneToOneField(parent_link=True, primary_key=True, to='examples.Updated', auto_created=True, serialize=False)),
                ('title', models.CharField(verbose_name='Manual Check Title', max_length=512)),
                ('title_html', models.CharField(max_length=512)),
                ('description', models.TextField(null=True, verbose_name='Manual Check Description', blank=True)),
                ('description_html', models.TextField(null=True, blank=True)),
                ('url', models.URLField(null=True, verbose_name='Manual Check URL', blank=True)),
            ],
            options={
                'ordering': ['rule', 'title'],
                'verbose_name_plural': 'Manual Checks',
                'verbose_name': 'Manual Check',
            },
            bases=('examples.updated',),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('updated_ptr', models.OneToOneField(parent_link=True, primary_key=True, to='examples.Updated', auto_created=True, serialize=False)),
                ('rule_id', models.CharField(unique=True, verbose_name='Rule ID', max_length=64)),
                ('scope', models.CharField(default='0', verbose_name='Rule Scope', choices=[('0', 'Unknown'), ('1', 'Element'), ('2', 'Page'), ('3', 'Website')], max_length=1)),
                ('mc_properties', models.CharField(verbose_name='Comma separated list of cache properties for manual check views', max_length=250)),
                ('resource_properties', models.CharField(verbose_name='Comma separated list of cache properties and attributes used by the rule', max_length=250)),
                ('language_dependancy', models.CharField(default='', verbose_name='Language codes separated by commas', max_length=100)),
                ('cache_dependency', models.CharField(default='unknown', verbose_name='Cache the validation function uses', choices=[('unknown', 'Unknown'), ('abbreviations_cache', 'Abbreviations Cache'), ('color_contrast_cache', 'Color Contrast Cache'), ('controls_cache', 'Controls Cache'), ('headings_landmarks_cache', 'Headings/Landmarks Cache'), ('images_cache', 'Images Cache'), ('languages_cache', 'Languages Cache'), ('links_cache', 'Links Cache'), ('lists_cache', 'Lists Cache'), ('media_cache', 'Media Cache'), ('tables_cache', 'Tables Cache')], max_length=25)),
                ('validation', models.TextField(null=True, verbose_name='Javascript code for validation function', blank=True)),
                ('nls_rule_id', models.CharField(verbose_name='Translated Rule ID', max_length=64)),
                ('definition', models.CharField(verbose_name='Rule Definition', max_length=512)),
                ('definition_html', models.CharField(default='', max_length=512)),
                ('summary', models.CharField(verbose_name='Rule Summary (shorter version of definition)', max_length=128)),
                ('summary_html', models.CharField(default='', max_length=256)),
                ('summary_text', models.CharField(default='', max_length=128)),
                ('target_resource_desc', models.CharField(verbose_name='Summary of the types of element definitions this rule tests', max_length=512)),
                ('target_resource_desc_html', models.CharField(max_length=512)),
                ('purpose_1', models.CharField(verbose_name='Purpose 1 (i.e how does the rule help people with disabilites)', max_length=512)),
                ('purpose_1_html', models.CharField(default='', max_length=512)),
                ('purpose_2', models.CharField(null=True, verbose_name='Purpose 2', max_length=512, blank=True)),
                ('purpose_2_html', models.CharField(default='', max_length=512)),
                ('purpose_3', models.CharField(null=True, verbose_name='Purpose 3', max_length=512, blank=True)),
                ('purpose_3_html', models.CharField(default='', max_length=512)),
                ('purpose_4', models.CharField(null=True, verbose_name='Purpose 4', max_length=512, blank=True)),
                ('purpose_4_html', models.CharField(default='', max_length=512)),
                ('rule_result_mc_s', models.CharField(null=True, verbose_name='Rule Result Message: One manual check', max_length=512, blank=True)),
                ('rule_result_mc_p', models.CharField(null=True, verbose_name='Rule Result Message: More than one manual check', max_length=512, blank=True)),
                ('rule_result_fail_s', models.CharField(null=True, verbose_name='Rule Result Message: One failed element', max_length=512, blank=True)),
                ('rule_result_fail_p', models.CharField(null=True, verbose_name='Rule Result Message: More than one failed element', max_length=512, blank=True)),
                ('rule_result_hidden_s', models.CharField(null=True, verbose_name='Rule Result Message: One hidden element', max_length=512, blank=True)),
                ('rule_result_hidden_p', models.CharField(null=True, verbose_name='Rule Result Message: More than one hidden element', max_length=512, blank=True)),
                ('rule_result_na', models.CharField(null=True, verbose_name='Rule Result Message: Not Applicable Message', max_length=512, blank=True)),
                ('rule_category', models.ForeignKey(related_name='rules', to='ruleCategories.RuleCategory')),
                ('target_resources', models.ManyToManyField(to='markup.ElementDefinition', related_name='rules')),
                ('wcag_primary', models.ForeignKey(related_name='rules', to='wcag20.WCAG20_SuccessCriterion')),
                ('wcag_related', models.ManyToManyField(to='wcag20.WCAG20_SuccessCriterion', related_name='related_rules')),
            ],
            options={
                'ordering': ['rule_id'],
                'verbose_name_plural': 'Rules',
                'verbose_name': 'Rule',
            },
            bases=('examples.updated',),
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('updated_ptr', models.OneToOneField(parent_link=True, primary_key=True, to='examples.Updated', auto_created=True, serialize=False)),
                ('technique_id', models.CharField(unique=True, verbose_name='Technique ID', max_length=64)),
                ('type', models.CharField(default='PR', verbose_name='Technique Type', choices=[('PR', 'Preferred technique, should be used whenever possible'), ('SP', 'Special case, should only be used when preferred techniques are not possible')], max_length=2)),
                ('title', models.CharField(verbose_name='Technique Title', max_length=512)),
                ('title_html', models.CharField(default='', max_length=1024)),
                ('abbrev', models.CharField(null=True, verbose_name='Technique Abbreviation', max_length=128, blank=True)),
                ('abbrev_html', models.CharField(default='', max_length=256)),
                ('notes', models.TextField(null=True, verbose_name='Technique Notes', blank=True)),
                ('notes_html', models.TextField(default='')),
                ('url', models.URLField(null=True, verbose_name='Technique URL', blank=True)),
                ('rule', models.ForeignKey(related_name='techniques', to='examples.Rule')),
            ],
            options={
                'ordering': ['rule', 'type'],
                'verbose_name_plural': 'Techniques',
                'verbose_name': 'Technique',
            },
            bases=('examples.updated',),
        ),
        migrations.AddField(
            model_name='updated',
            name='updated_editor',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualcheck',
            name='rule',
            field=models.ForeignKey(related_name='manual_checks', to='examples.Rule'),
        ),
    ]
