"""
Django settings for oaa_examples_django project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import django
from os.path import join, abspath, dirname
import json

here = lambda *dirs: join(abspath(dirname(__file__)), *dirs)
root = lambda *dirs: join(abspath(here("..","..")), *dirs)
BASE_DIR = here("", "")
print("BASE_DIR: " + BASE_DIR)
APP_DIR = root("")
print("APP_DIR: " + APP_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x)%i7dem&c(2*jh-hjtjayy0_1#%_&gpens(0u(rv$h$n3s3wr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DJANGO_ROOT = os.path.dirname(os.path.realpath(django.__file__))
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

STATIC_URL = '/static/'
print("STATIC_URL: " + STATIC_URL)
STATIC_ROOT = join(BASE_DIR, 'static/')
print("STATIC_ROOT: " + STATIC_ROOT)

STATICFILES_DIRS = (
    join(APP_DIR, "oaa_examples_django/static"),
)
print("STATICFILES_DIRS: " + str(STATICFILES_DIRS))

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'examples',
    'markup',
    'ruleCategories',
    'wcag20',
    'abouts'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'oaa_examples_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SITE_ROOT, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oaa_examples_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
SECRET_FILE = join(BASE_DIR, 'secrets.json')

with open(SECRET_FILE) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets = secrets):
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {0} environement variable".format(setting)
        raise ImproperlyConfigured(error_msg)


DATABASES = {
    'default': get_secret("DATABASES")
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True
